schema_version: 1

context:
  version: 1.0.5
  lib_version: 1.0.0

package:
  name: osqp
  version: ${{ version }}

source:
  url: https://github.com/osqp/osqp-python/archive/refs/tags/v${{ version }}.tar.gz
  sha256: fe555180a1ad7e25bb3e3df787a1539de664a9fd0b1639271f8d5553bc22049e
  patches:
    - patches/0001-Link-against-shared-osqp-library.patch
    # remove pytorch imports on ppc; the actual test is skipped below, this is to unbreak collection
    - if: ppc64le
      then: patches/0002-Remove-pytorch-related-imports.patch
    - patches/0003-disable-codegen-ABI-is-not-compatible.patch

build:
  number: 2
  script:
    - if: unix
      then:
        - export SETUPTOOLS_SCM_PRETEND_VERSION=${{ version }}
        - export CMAKE_GENERATOR=Ninja
        - export CMAKE_INCLUDE_PATH=$PREFIX/include
    - if: win
      then:
        - set "SETUPTOOLS_SCM_PRETEND_VERSION=${{ version }}"
        # on Windows, we cannot set CMAKE_GENERATOR directly due to the issue
        # https://github.com/scikit-build/scikit-build-core/issues/1089
        - set "SKBUILD_CMAKE_ARGS=-G Ninja"
        - set "CMAKE_INCLUDE_PATH=%LIBRARY_INC%"
    - ${{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
    - pybind11
  host:
    - python
    - scikit-build-core
    - setuptools_scm
    - pip
    - numpy
    - libosqp =${{ lib_version }}
    - setuptools
  run:
    - python
    - qdldl-python
    - jinja2
    - joblib
    - scipy
  run_constraints:
    - if: win
      then: mkl >=2022.0

tests:
  - python:
      imports:
        - osqp
        - osqp.codegen
  - requirements:
      run:
        - if: x86_64
          then: blas * mkl
        - pytest
        - if: not ppc64le
          then: pytorch
    script:
      interpreter: python
      content:
        - import pytest
        # codegen tests are disabled because they require an incompatible ABI, see patches
        - 'tests_to_skip = "codegen"'
        # skip test that takes 90%+ of test suite runtime (and is xfailed anyway)
        - if: aarch64 or ppc64le
          then:
            - 'tests_to_skip += " or test_multithread"'
        # we don't have pytorch on ppc; skip test module that needs it
        - if: ppc64le
          then:
            - 'tests_to_skip += " or nn_test.py"'
        - 'args = ["--pyargs", "osqp", "-k", f"not ({tests_to_skip})"]'
        - 'print(f"running pytest with args: {args}")'
        - 'pytest.main(args)'

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Python interface for OSQP, the Operator Splitting QP Solver
  description: |
    Python interface for OSQP, the Operator Splitting QP Solver.

    To use the `codegen` interface, install `cmake` and an appropriate
    compiler version. (We don't install this by default.)
  homepage: https://osqp.org/
  repository: http://github.com/osqp/osqp-python
  documentation: https://osqp.org/

extra:
  recipe-maintainers:
    - sebp
    - djsutherland
    - h-vetinari
    - bstellato
    - gbanjac
    - jayfurmanek
